### ISSUE TITLE
[DISCUSS] Implement `display_id` in protocol v5.1

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/nel#4]
See https://github.com/n-riesco/ijavascript/issues/93#issuecomment-275861542

@rgbkrk What would be the use case for giving the user access to `display_id`?

IJavascript handles access to each cell by means of the object `$$`. Each cell has its own `$$`. And for this reason, there is no need to know the `display_id`; we only need to know the `$$` of each cell. Here's an example of how to use  the `$$` of multiple cells:

```js
// In[1]
$$.async();

const $1 = global.$$;
const console1 = global.console;

console1.log("This goes to Out[1]");
$1.text("and this too");

// In[2]
$$.async();

const $2 = global.$$;
const console2 = global.console;

console2.log("This goes to Out[2]");
$2.text("and this too");

// In[3]
console1.log("This goes to Out[1]");
$1.text("and this too");
$1.done(); // close cell 1 output

console2.log("This goes to Out[2]");
$2.text("and this too");
$2.done(); // close cell 2 output

console.log("This goes to Out[3]");
"and this too";
```

**Comment by rgbkrk** [comment]
https://github.com/jupyter/notebook/pull/1879 has the best demonstration, since it includes examples. Note that the only published notebook app (at time of writing) to support updating displays is nteract -- it's implemented across the jupyter notebook and IPython, it's not published (yet).

The primary motivator is to be able to update outputs (as opposed to clear + append).

In IPython a user can run:

```python
IPython.display.display({
  "text/html": "<progress style='width:100%' max=100 value=50 />"
}, raw=True, display_id="test")
```

and then later write:

```python
IPython.display.display({
  "text/html": "<progress style='width:100%' max=100 value=75 />"
}, raw=True, display_id="test", update=True)
```

and it will update that prior output.

![screen shot 2017-01-28 at 11 40 58 am](https://cloud.githubusercontent.com/assets/836375/22399306/ab422a94-e54e-11e6-85ac-8440cff3243b.png)

**Comment by rgbkrk** [comment]
In nteract, if you load the example notebook "Named Display Updates" from the "File  -> Open Example notebooks" menu you'll find a nice narrative doc on the user experience of updating displays. On disk, if running from master of nteract it's in `example-notebooks/display-updates.ipynb`.

**Comment by rgbkrk** [comment]
Features like these may or may not be most useful for final end users - they should be available for libraries that build on top of IJavaScript to build rich experiences.

**Comment by n-riesco** [comment]
I don't think users should be allowed to set `display_id`.

It isn't really needed (frontends already can identify the cell using the `msg_id` of `execution_request`).

I'm obviously biased, but I think the solution in IJavascript is simpler and more transparent for the user. Here's a mock of how IPython could replicate it:

![screenshot from 2017-01-28 21-13-04](https://cloud.githubusercontent.com/assets/6199391/22399881/9b0bb46a-e59e-11e6-8fcb-2f12ddd31fcc.png)

---

Two questions about `transient` (assuming I'm reading the spec correctly):

- Are the `data` (added to the output by means of `update_display_data`) preserved in the `.ipynb` file? Or am I reading too much in `display_id` being defined inside `transient`?. It'd be more useful if they were.

- How does the frontend know that there are no more output updates? I see this being an issue for `nbconvert` (if the updates were to be preserved in the `.ipynb` file).

**Comment by rgbkrk** [comment]
> Are the data (added to the output by means of update_display_data) preserved in the .ipynb file?

The data is preserved into the notebook file -- this allows for updating graphics over time without having to use ipywidgets and still end up with the serialized representation.

> How does the frontend know that there are no more output updates? I see this being an issue for nbconvert (if the updates were to be preserved in the .ipynb file).

It can't know, and that's ok.

**Comment by n-riesco** [comment]
Moved to https://github.com/n-riesco/ijavascript/issues/95
